# Generated by Django 3.1.4 on 2020-12-18 06:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyname', models.CharField(max_length=200)),
                ('registration_no', models.IntegerField()),
                ('primary_location', models.CharField(max_length=300)),
                ('description', models.CharField(default='The right agency for you', max_length=300)),
                ('agency_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['agencyname'],
            },
        ),
    ]
